### ISSUE TITLE
InvalidCastException: Unable to cast object of type 'String' to type 'HexBigInteger'.

### ISSUE THREAD

**Issue by iurii-voya-games** [thirdweb-dev/unity-sdk#200]
Hi!

[ThirdwebInterceptor.InterceptSendRequestAsync](https://github.com/thirdweb-dev/unity-sdk/blob/main/Assets/Thirdweb/Core/Scripts/ThirdwebInterceptor.cs#L37) returns a `strings` when `request.Method == "eth_chainId"`. Specifically, it returns `HexBigInteger.HeValue`. That causes the exception in [ClientBase.SendRequestAsync](https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.JsonRpc.Client/ClientBase.cs#L19) -- it is casting a `string` to `HexBigInteger`.

Is this behaviour intended?

Thanks.

**Comment by 0xFirekeeper** [comment]
I believe this is intended, how are you getting the exception, using our APIs?

**Comment by Vingator** [comment]
Hey @0xFirekeeper , 
Thanks a lot for the response, I work with @iurii-voya-games, and answering your question, yes, we're using your API invoking `sdk.Wallet.SwitchNetwork`. 

It fails in the process of fetching the current chainId in the wallet provider `ThirdwebMetamask.PrepareNetworkForSwitch`, as `Nethereum.RPC.Eth.EthChainId` expects a `HexBigInteger` and not a `string`

We also spotted another issue following the flow of  the SwitchNetwork method, I can open a separated ticket if necessary, but as a quick explanation `ThirdwebSession.EnsureCorrectNetwork` method throws a `UnityException` even though the switch network happened which doesn't allow the chainId to be changed inside the API. That happens because Metamask returns null when the network was successfully switched, as stated by their documentation: https://docs.metamask.io/wallet/reference/wallet_switchethereumchain/
