### ISSUE TITLE
Is it ok, for the CORE scripts, to rely a lot on the ThirdwebManager class?

### ISSUE THREAD

**Issue by luismasuelli** [thirdweb-dev/unity-sdk#80]
When I read [this documentation page](https://portal.thirdweb.com/unity/thirdwebmanager), it makes me understand that the ThirdwebManager class (which goes intro a prefab) is optional. However, in the current state of the code (main branch, so far) I see that the CORE scripts' classes have many references to ThirdwebManager.Instance.SDK. All these ones will fail (because of null / not assigned, if not something worse) if no prefab is in the scene, turning the prefab into a mandatory object. Also, that pattern itself looks a bit smelly to me, when the counterfactual would be to pass proper SDK references to avoid these things (we'd also get the ability to get).

I forked this repository and created a new branch addressing these topics. Is it OK if I send this branch for you to review?

**Comment by 0xFirekeeper** [comment]
Hey, the ThirdwebManager is not needed for WebGL if you build and run it in a browser context, which is the only way to test, as it uses the typescript SDK. It is required for Native platforms. It's also highly recommended to use it for WebGL though as we're currently working on moving as much code as possible to native c# except for the mandatory core, meaning we'll be using it to reference the active SDK. Feel free to share your suggestions, you can also open a ticket on the thirdweb discord and mention Firekeeper if you have any suggestions 👍

**Comment by 0xFirekeeper** [comment]
I understand the pain points associated with wanting to deal with multiple SDKs, and I understand you want to decouple the code from the singleton, however to stay in line with WebGL and keep it simple for users through the ThirdwebManager instance, I'd rather you share what you'd like to be made easier when editing your SDK, then we can work on fixing that. For instance, previously it was difficult to handle a situation like a partially gasless app, and now you can with the Transaction api, rather than passing an entirely different sdk with some different variables and managing all of this, etc.

**Comment by 0xFirekeeper** [comment]
Closing this after our discussion, you can keep working on the PR if you like and I'll take a second look after 3.0 is out 🤝
